//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GendacBluesheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class bluesheetdocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bluesheetdocument()
        {
            this.buyers = new HashSet<buyer>();
            this.redFlags = new HashSet<redFlag>();
            this.strengths = new HashSet<strength>();
        }
    
        public string compName { get; set; }
        public string oppType { get; set; }
        public Nullable<int> oppSize { get; set; }
        public Nullable<System.DateTime> oppTime { get; set; }
        public int id { get; set; }
        public string location { get; set; }
        public Nullable<int> clientAge { get; set; }
        public string turnOver { get; set; }
        public string respMode { get; set; }
        public string industry { get; set; }
        public string clientComp { get; set; }
        public string techDependancy { get; set; }
        public string advisable { get; set; }
        public string extDev { get; set; }
        public string extDevSpend { get; set; }
        public Nullable<bool> doNothing { get; set; }
        public string otherComp { get; set; }
        public Nullable<bool> intResources { get; set; }
        public string budgetElse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buyer> buyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<redFlag> redFlags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<strength> strengths { get; set; }
    }
}
