//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GendacBluesheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class competitor
    {
        public string competType { get; set; }
        public string competDescr { get; set; }
        public Nullable<int> id { get; set; }
        public int competID { get; set; }
    
        public virtual bluesheetdocument bluesheetdocument { get; set; }
    }
}
