//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GendacBluesheet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GendacBlueSheetEntities : DbContext
    {
        public GendacBlueSheetEntities()
            : base("name=GendacBlueSheetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bluesheetdocument> bluesheetdocuments { get; set; }
        public virtual DbSet<buyer> buyers { get; set; }
        public virtual DbSet<redFlag> redFlags { get; set; }
        public virtual DbSet<strength> strengths { get; set; }
    }
}
