//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GendacBluesheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class redFlag
    {
        public string redFlag1 { get; set; }
        public string strategy { get; set; }
        public Nullable<int> id { get; set; }
        public int redFlagID { get; set; }
    
        public virtual bluesheetdocument bluesheetdocument { get; set; }
    }
}
