//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GendacBluesheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class strength
    {
        public string strength1 { get; set; }
        public string leverage { get; set; }
        public Nullable<int> id { get; set; }
        public int strengthID { get; set; }
    
        public virtual bluesheetdocument bluesheetdocument { get; set; }
    }
}
